apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hotify-bark-server.fullname" . }}-data
  labels:
    {{- include "hotify-bark-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}